# This is a basic workflow to help you get started with Actions
# This file was contributed by EdwinBetancourt@outlook.com
# from ERP Consultores y Asociados, C.A

name: ADempiere Publish

on:
  release:
    types:
      - published

jobs:
  build-withholding:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '11' ]
        os: [ 'ubuntu-latest' ] # , 'macos-latest', 'windows-latest' ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-package: 'jdk'
            java-version: ${{ matrix.java }}
            architecture: x64

      - name: Uncompress Adempiere.jar file
        run: |
          mkdir dependences
          unzip -j Adempiere.zip Adempiere/lib/Adempiere.jar -d dependences/

      - name: Compile
        uses: gradle/gradle-build-action@v2.1.5
        with:
          gradle-version: 7.1
          arguments: build

      - name: Uncompress build binaries
        run: unzip build/release/Withholding.zip -d build/release/

      - name: Upload Withholding.jar
        uses: actions/upload-artifact@v3
        with:
          name: Withholding.jar
          path: build/release/Withholding.jar

      - name: Upload migration folder
        uses: actions/upload-artifact@v3
        with:
          name: migration.zip
          path: build/release/migration

      - name: Upload dist files
        uses: actions/upload-artifact@v3
        with:
          name: Withholding.zip
          path: |
            build/release/migration
            build/release/Withholding.jar

  # Publish dist binaries to application
  publish-dist:
    name: Upload ADempiere-Vue binaries
    needs:
      - build-withholding
    runs-on: ubuntu-latest
    steps:
      - name: Download build dist app
        uses: actions/download-artifact@v2
        with:
          name: Withholding.zip

      - run: ls

      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: 'Withholding.zip'
          path: './'

      - name: Publish binary in repository
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'Withholding.zip'
