# This is a basic workflow to help you get started with Actions
# This file was contributed by EdwinBetancourt@outlook.com
# from ERP Consultores y Asociados, C.A

name: Withholding Publish

on:
  release:
    types:
      - published

jobs:
  build-withholding:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '11' ]
        os: [ 'ubuntu-latest' ] # , 'macos-latest', 'windows-latest' ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-package: 'jdk'
            java-version: ${{ matrix.java }}
            architecture: x64

      - name: Get adempiere source
        run: |
          download_repo="https://github.com/erpcya/adempiere/releases/download/3.9.3-rs-4.5/Adempiere_393LTS.zip"
          wget $download_repo -c -O Adempiere.zip

      - name: Uncompress Adempiere.jar file
        run: |
          mkdir dependences
          unzip -j Adempiere.zip Adempiere/lib/Adempiere.jar -d dependences/

      - name: Compile
        uses: gradle/gradle-build-action@v2.1.5
        with:
          gradle-version: 7.1
          arguments: build

      - name: Prepare Dist Release
        uses: gradle/gradle-build-action@v2.1.5
        with:
          gradle-version: 7.1
          arguments: createRelease

      - name: Uncompress build binaries
        run: unzip build/release/Withholding.zip -d build/release/

      - name: Artifact upload Withholding.jar
        uses: actions/upload-artifact@v3
        with:
          name: Withholding.jar
          path: build/release/Withholding.jar

      - name: Artifact upload Adempiere.jar
        uses: actions/upload-artifact@v3
        with:
          name: Adempiere.jar
          path: dependences/Adempiere.jar

      - name: Artifact upload migration folder
        uses: actions/upload-artifact@v3
        with:
          name: migration.zip
          path: build/release/migration

      - name: Artifact upload binay and migration
        uses: actions/upload-artifact@v3
        with:
          name: Withholding.zip
          path: |
            build/release/migration
            build/release/Withholding.jar

  # Publish dist binary
  publish-ghpk:
    name: GH Packages Publish
    needs: build-withholding
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-package: 'jdk'
            java-version: '11'
            architecture: x64

      - name: Download Adempiere.jar
        uses: actions/download-artifact@v3
        with:
          name: Adempiere.jar
          path: dependences/

      - run: echo '${{ toJSON(github) }}'
      - name: Publish on GH Packages
        uses: gradle/gradle-build-action@v2.1.5
        with:
          gradle-version: 7.1
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_REPOSITORY_OWNER: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          # GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      - run: ls
      - run: ls build/publications
      - run: ls build/generated

  # Publish dist binairy and migration
  publish-all:
    name: GH Publish all
    needs:
      - build-withholding
    runs-on: ubuntu-latest
    steps:
      - name: Download build all
        uses: actions/download-artifact@v3
        with:
          name: Withholding.zip
          path: Withholding

      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: 'Withholding.zip'
          path: './Withholding'

      - name: Publish all in repository
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'Withholding.zip'

  # Publish dist binaries to application
  publish-dist:
    name: GH Publish Withholding binary
    needs:
      - build-withholding
    runs-on: ubuntu-latest
    steps:
      - name: Download build dist app
        uses: actions/download-artifact@v3
        with:
          name: Withholding.jar

      - name: Publish binary in repository
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'Withholding.jar'

  # Publish dist binaries to application
  publish-migration:
    name: GH Publish Withholding migration
    needs:
      - build-withholding
    runs-on: ubuntu-latest
    steps:
      - name: Download build dist app
        uses: actions/download-artifact@v3
        with:
          name: migration.zip
          path: migration

      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: 'migration.zip'
          path: './migration'

      - name: Publish binary in repository
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'migration.zip'
